name: Destroy Azure Infrastructure (Terraform)

on:
  workflow_dispatch:  # Manual trigger from Actions tab

env:
  ENVIRONMENT: dev
  LOCATION: East US
  IMAGE_NAME: ghcr.io/mani7reddy/dotnethelloworld:latest

jobs:
  destroy:
    name: Destroy Infra
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # -----------------------------
      # Checkout Code
      # -----------------------------
      - name: Checkout Code
        uses: actions/checkout@v4

      # -----------------------------
      # Setup Terraform
      # -----------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # -----------------------------
      # Azure Login
      # -----------------------------
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      # -----------------------------
      # Terraform Init
      # -----------------------------
      - name: Terraform Init
        working-directory: infra
        run: |
          echo "Initializing Terraform backend..."
          terraform init -input=false -reconfigure -upgrade
          echo "Terraform initialization complete."
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      # -----------------------------
      # Terraform Destroy
      # -----------------------------
      - name: Terraform Destroy
        working-directory: infra
        run: |
          echo " Destroying Azure Infrastructure for environment: ${{ env.ENVIRONMENT }} ..."
          terraform destroy -lock=false -auto-approve \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -var="location=${{ env.LOCATION }}" \
            -var="image_name=${{ env.IMAGE_NAME }}"
          echo " Terraform destroy completed successfully."
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
