name: Deploy .NET App to Azure Container Apps via Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ENVIRONMENT: dev
  LOCATION: East US
  IMAGE_NAME: ghcr.io/${{ github.actor }}/dotnethelloworld:latest

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # 1️⃣ Checkout code
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # 2️⃣ Set up .NET SDK
      # -------------------------------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # -------------------------------
      # 3️⃣ Build and publish app
      # -------------------------------
      - name: Build and publish
        run: |
          dotnet restore
          dotnet publish -c Release -o app/publish

      # -------------------------------
      # 4️⃣ Log in to GitHub Container Registry (GHCR)
      # -------------------------------
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # -------------------------------
      # 5️⃣ Build and push Docker image
      # -------------------------------
      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # -------------------------------
      # 6️⃣ Log in to Azure
      # -------------------------------
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # -------------------------------
      # 7️⃣ Set up Terraform
      # -------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # -------------------------------
      # 8️⃣ Initialize Terraform
      # -------------------------------
      - name: Terraform Init
        working-directory: infra
        run: terraform init

      # -------------------------------
      # 9️⃣ Apply Terraform
      # -------------------------------
      - name: Terraform Apply
        working-directory: infra
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          LOCATION: ${{ env.LOCATION }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          terraform apply -auto-approve \
            -var="environment=$ENVIRONMENT" \
            -var="location=$LOCATION" \
            -var="image_name=$IMAGE_NAME"

      # -------------------------------
      # 🔟 Output URL
      # -------------------------------
      - name: Get App URL
        working-directory: infra
        run: |
          echo "🌍 Deployed App URL:"
          terraform output app_url

